import { db } from "@workspace/db";
import { evidenceSourcesTable } from "@workspace/db/schema";

const SOURCES = [
  {
    id: "rss_reuters",
    name: "Reuters Middle East",
    type: "rss",
    url: "https://feeds.reuters.com/reuters/worldNews",
    isEnabled: true,
    fetchFrequencyMinutes: 60,
  },
  {
    id: "rss_ap",
    name: "AP World News",
    type: "rss",
    url: "https://rsshub.app/apnews/topics/apf-intlnews",
    isEnabled: true,
    fetchFrequencyMinutes: 60,
  },
  {
    id: "rss_aljazeera",
    name: "Al Jazeera Middle East",
    type: "rss",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    isEnabled: true,
    fetchFrequencyMinutes: 60,
  },
  {
    id: "rss_bbc_world",
    name: "BBC World News",
    type: "rss",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "rss_guardian",
    name: "The Guardian World",
    type: "rss",
    url: "https://www.theguardian.com/world/rss",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "rss_foreignaffairs",
    name: "Foreign Affairs",
    type: "rss",
    url: "https://www.foreignaffairs.com/rss.xml",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "rss_foreignpolicy",
    name: "Foreign Policy",
    type: "rss",
    url: "https://foreignpolicy.com/feed/",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "rss_brookings",
    name: "Brookings Institution",
    type: "rss",
    url: "https://www.brookings.edu/feed/",
    isEnabled: true,
    fetchFrequencyMinutes: 240,
  },
  {
    id: "rss_carnegie",
    name: "Carnegie Endowment for International Peace",
    type: "rss",
    url: "https://carnegieendowment.org/rss/solr/?subp=68",
    isEnabled: true,
    fetchFrequencyMinutes: 240,
  },
  {
    id: "rss_csis",
    name: "CSIS - Center for Strategic and International Studies",
    type: "rss",
    url: "https://www.csis.org/analysis/feed",
    isEnabled: true,
    fetchFrequencyMinutes: 240,
  },
  {
    id: "rss_armscontrol",
    name: "Arms Control Association",
    type: "rss",
    url: "https://www.armscontrol.org/rss.xml",
    isEnabled: true,
    fetchFrequencyMinutes: 360,
  },
  {
    id: "rss_middleeasteye",
    name: "Middle East Eye",
    type: "rss",
    url: "https://www.middleeasteye.net/rss",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "rss_arabnews",
    name: "Arab News",
    type: "rss",
    url: "https://www.arabnews.com/rss.xml",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "rss_iranintl",
    name: "Iran International",
    type: "rss",
    url: "https://www.iranintl.com/en/feed",
    isEnabled: true,
    fetchFrequencyMinutes: 60,
  },
  {
    id: "rss_crisisgroup",
    name: "International Crisis Group",
    type: "rss",
    url: "https://www.crisisgroup.org/rss.xml",
    isEnabled: true,
    fetchFrequencyMinutes: 360,
  },
  {
    id: "gnews_iran_peace",
    name: "Google News: Iran Peace Proposals",
    type: "rss",
    url: "https://news.google.com/rss/search?q=Iran+peace+proposal+nuclear+deal&hl=en-US&gl=US&ceid=US:en",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "gnews_iran_diplomacy",
    name: "Google News: Iran Diplomacy",
    type: "rss",
    url: "https://news.google.com/rss/search?q=Iran+diplomatic+framework+ceasefire+negotiation&hl=en-US&gl=US&ceid=US:en",
    isEnabled: true,
    fetchFrequencyMinutes: 120,
  },
  {
    id: "gdelt",
    name: "GDELT Project (Iran Conflict Articles)",
    type: "gdelt",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    isEnabled: true,
    fetchFrequencyMinutes: 60,
  },
  {
    id: "acled",
    name: "ACLED Armed Conflict Database",
    type: "acled",
    url: "https://api.acleddata.com/acled/read/",
    isEnabled: true,
    fetchFrequencyMinutes: 1440,
  },
];

export async function seedSources(): Promise<void> {
  for (const s of SOURCES) {
    await db.insert(evidenceSourcesTable).values(s).onConflictDoNothing();
  }
}
