import { db } from "@workspace/db";
import { stakeholdersTable } from "@workspace/db/schema";

const STAKEHOLDERS = [
  {
    id: "iran", name: "Iran", role: "core_principal", region: "Middle East", flag: "🇮🇷",
    goals: "Regime survival, nuclear deterrence, regional hegemony, sanction relief",
    redLines: "Regime change, full nuclear dismantlement, direct military attack on soil",
    preferredOutcomes: "Sanctions partial deal, regional framework recognizing Iranian sphere",
    constraints: "Economic pressure, internal factional divisions, IRGC autonomy",
    communicationStyle: "Strategic ambiguity, calibrated escalation, back-channel diplomacy",
  },
  {
    id: "us", name: "United States", role: "core_principal", region: "North America", flag: "🇺🇸",
    goals: "Non-proliferation, regional stability, protecting Israel, allied reassurance",
    redLines: "Iranian nuclear weapon acquisition, direct attacks on US forces or allies",
    preferredOutcomes: "Sanctions partial deal or JCPOA-plus framework",
    constraints: "Domestic politics, congressional AIPAC pressure, allied coordination",
    communicationStyle: "Multilateral framing, maximum pressure alternating with dialogue",
  },
  {
    id: "israel", name: "Israel", role: "core_principal", region: "Middle East", flag: "🇮🇱",
    goals: "Prevent Iranian nuclear capability, degrade proxy networks, maintain military superiority",
    redLines: "Iranian nuclear breakout, Hezbollah precision missiles targeting cities",
    preferredOutcomes: "Broad sanctions regime, military option preserved",
    constraints: "International legitimacy concerns, US approval for major operations",
    communicationStyle: "Deterrence signaling, unilateral action doctrine",
  },
  {
    id: "saudi_arabia", name: "Saudi Arabia", role: "gulf_state", region: "Gulf", flag: "🇸🇦",
    goals: "Counter Iranian influence, oil market stability, regional security architecture",
    redLines: "Iranian attack on Saudi infrastructure, Houthi escalation",
    preferredOutcomes: "Regional framework including Iranian recognition of Saudi sphere",
    constraints: "Vision 2030 economic diversification, OPEC coordination",
    communicationStyle: "Transactional diplomacy, bilateral over multilateral",
  },
  {
    id: "uae", name: "United Arab Emirates", role: "gulf_state", region: "Gulf", flag: "🇦🇪",
    goals: "Trade hub stability, neutrality preservation, Iran economic channels",
    redLines: "Disruption of Strait of Hormuz, attack on UAE soil",
    preferredOutcomes: "Informal deescalation preserving trade access",
    constraints: "Significant Iranian trade volumes, Dubai financial hub concerns",
    communicationStyle: "Pragmatic hedging, discreet back-channels",
  },
  {
    id: "qatar", name: "Qatar", role: "gulf_state", region: "Gulf", flag: "🇶🇦",
    goals: "Mediation role, gas export security, Hamas relations",
    redLines: "Forced alignment against Iran",
    preferredOutcomes: "Diplomatic framework with Qatar as key broker",
    constraints: "Shared North Dome/South Pars gas field with Iran",
    communicationStyle: "Active mediation, multi-directional diplomacy",
  },
  {
    id: "oman", name: "Oman", role: "gulf_state", region: "Gulf", flag: "🇴🇲",
    goals: "Neutrality, back-channel facilitation, Strait of Hormuz security",
    redLines: "Being drawn into conflict",
    preferredOutcomes: "Quiet diplomacy leading to deescalation",
    constraints: "Geographic vulnerability, traditional neutral role",
    communicationStyle: "Quiet diplomacy, confidential facilitation",
  },
  {
    id: "kuwait", name: "Kuwait", role: "gulf_state", region: "Gulf", flag: "🇰🇼",
    goals: "Security under US umbrella, stability, oil revenue",
    redLines: "Repeat of 1990 invasion scenario",
    preferredOutcomes: "US security guarantees maintained, regional stability",
    constraints: "Significant Shia population, border with Iraq",
    communicationStyle: "Cautious, multilateral coalition-building",
  },
  {
    id: "bahrain", name: "Bahrain", role: "gulf_state", region: "Gulf", flag: "🇧🇭",
    goals: "Regime survival, US basing, countering Iranian influence on Shia population",
    redLines: "Iranian-backed domestic destabilization",
    preferredOutcomes: "Strong US security presence, Abraham Accords expansion",
    constraints: "Shia majority population, Iranian influence via religious networks",
    communicationStyle: "Strong alignment with US/Saudi position",
  },
  {
    id: "egypt", name: "Egypt", role: "regional_broker", region: "North Africa", flag: "🇪🇬",
    goals: "Stability, Gaza ceasefire, canal revenues, avoiding regional spillover",
    redLines: "Destabilization of Gaza-Egypt border",
    preferredOutcomes: "Humanitarian mini-deal, Gaza ceasefire",
    constraints: "Economic fragility, Muslim Brotherhood suppression, US aid dependency",
    communicationStyle: "Pragmatic broker, ceasefire facilitation emphasis",
  },
  {
    id: "turkey", name: "Turkey", role: "regional_broker", region: "Middle East", flag: "🇹🇷",
    goals: "Regional power projection, NATO hedging, economic relations with Iran",
    redLines: "Kurdish territorial gains, loss of Syria influence",
    preferredOutcomes: "Regional framework with Turkish mediator role",
    constraints: "NATO membership vs. Russia/Iran relations, Kurdish issue",
    communicationStyle: "Strategic autonomy, Erdogan personalist diplomacy",
  },
  {
    id: "pakistan", name: "Pakistan", role: "regional_broker", region: "South Asia", flag: "🇵🇰",
    goals: "Avoid Iran-Pakistan border conflict, maintain economic corridor",
    redLines: "Iranian attack on Pakistani territory",
    preferredOutcomes: "Deescalation, economic engagement",
    constraints: "Economic crisis, IMF dependency, internal instability",
    communicationStyle: "Cautious engagement, Islamic solidarity framing",
  },
  {
    id: "iraq", name: "Iraq", role: "regional_broker", region: "Middle East", flag: "🇮🇶",
    goals: "Avoid becoming battleground, Iranian and US engagement balance",
    redLines: "US or Iranian forces using Iraqi territory for attacks",
    preferredOutcomes: "Regional stability, Iraqi sovereignty respected",
    constraints: "PMF-Iranian ties, US troop presence, political fragmentation",
    communicationStyle: "Balancing act between Iran and US",
  },
  {
    id: "jordan", name: "Jordan", role: "regional_broker", region: "Middle East", flag: "🇯🇴",
    goals: "Palestinian state solution, regional stability, US support",
    redLines: "Mass Palestinian refugee influx, loss of Jerusalem custodianship",
    preferredOutcomes: "Two-state solution framework, Gaza humanitarian deal",
    constraints: "Palestinian refugee population, economic vulnerability",
    communicationStyle: "Moderate diplomatic voice, quiet US alignment",
  },
  {
    id: "lebanon", name: "Lebanon", role: "regional_broker", region: "Middle East", flag: "🇱🇧",
    goals: "Avoiding total Hezbollah-Israel war, economic survival",
    redLines: "Israeli ground invasion, complete economic collapse",
    preferredOutcomes: "Limited ceasefire, Hezbollah restraint deal",
    constraints: "Hezbollah dominance, state failure, economic crisis",
    communicationStyle: "Fragmented government, Hezbollah parallel governance",
  },
  {
    id: "yemen", name: "Yemen (Houthis)", role: "regional_broker", region: "Middle East", flag: "🇾🇪",
    goals: "Recognition, end to Saudi blockade, solidarity with Palestinians",
    redLines: "Military defeat, total economic blockade",
    preferredOutcomes: "Negotiated end to war, Houthi political recognition",
    constraints: "Iranian proxy relationship, humanitarian catastrophe",
    communicationStyle: "Escalatory pressure via maritime attacks, propaganda",
  },
  {
    id: "syria", name: "Syria", role: "regional_broker", region: "Middle East", flag: "🇸🇾",
    goals: "Reconstruction support, end to sanctions, territorial control",
    redLines: "Israeli annexation of Golan, renewed civil war",
    preferredOutcomes: "Deescalation, Arab League readmission",
    constraints: "Reconstruction dependency, Russian/Iranian presence",
    communicationStyle: "Cautious, dependent on Russian-Iranian support",
  },
  {
    id: "france", name: "France", role: "external_power", region: "Europe", flag: "🇫🇷",
    goals: "European strategic autonomy, JCPOA preservation, Lebanon influence",
    redLines: "Nuclear proliferation, attack on French citizens",
    preferredOutcomes: "Multilateral diplomatic framework, JCPOA revival",
    constraints: "EU cohesion, US alliance, domestic politics",
    communicationStyle: "Multilateral institution leadership, Élysée initiative",
  },
  {
    id: "germany", name: "Germany", role: "external_power", region: "Europe", flag: "🇩🇪",
    goals: "JCPOA, non-proliferation, trade relations, regional stability",
    redLines: "Armed conflict threatening European security",
    preferredOutcomes: "Diplomatic resolution through E3+3 framework",
    constraints: "Post-WWII pacifism, EU partnership, US alliance",
    communicationStyle: "Economic diplomacy, multilateral consensus-building",
  },
  {
    id: "uk", name: "United Kingdom", role: "external_power", region: "Europe", flag: "🇬🇧",
    goals: "Transatlantic alignment, non-proliferation, Gulf security",
    redLines: "Iranian nuclear weapon, attacks on UK assets",
    preferredOutcomes: "Diplomatic framework aligned with US",
    constraints: "Post-Brexit reduced EU influence, US dependency",
    communicationStyle: "Strong US alignment, active E3 participant",
  },
  {
    id: "russia", name: "Russia", role: "external_power", region: "Eurasia", flag: "🇷🇺",
    goals: "Weaken US global position, arms sales, energy market share",
    redLines: "NATO expansion into Middle East, loss of Syrian base",
    preferredOutcomes: "Continued conflict draining US resources, Russian role preserved",
    constraints: "Ukraine war, sanctions, OPEC+ dynamics",
    communicationStyle: "Spoiler diplomacy, arms-supply leverage",
  },
  {
    id: "china", name: "China", role: "external_power", region: "East Asia", flag: "🇨🇳",
    goals: "Energy security, BRI expansion, reduce US regional dominance",
    redLines: "Conflict disrupting energy supplies or BRI",
    preferredOutcomes: "Saudi-Iran normalization maintained, regional stability",
    constraints: "Non-interference principle, US trade war",
    communicationStyle: "Multilateral non-interference, quiet influence expansion",
  },
  {
    id: "india", name: "India", role: "external_power", region: "South Asia", flag: "🇮🇳",
    goals: "Energy security (Iranian oil), Chabahar port access, strategic autonomy",
    redLines: "Disruption of Chabahar corridor",
    preferredOutcomes: "Stable Iran for energy imports and trade routes",
    constraints: "US sanctions pressure, Hindu nationalist domestic politics",
    communicationStyle: "Strategic autonomy, balancing act between US and Iran",
  },
  {
    id: "japan", name: "Japan", role: "external_power", region: "East Asia", flag: "🇯🇵",
    goals: "Energy security (Gulf oil), maritime security, US alliance",
    redLines: "Strait of Hormuz closure",
    preferredOutcomes: "Deescalation, energy flow guaranteed",
    constraints: "Constitutional pacifism, complete US alliance dependency",
    communicationStyle: "Quiet mediation, economic diplomacy",
  },
  {
    id: "south_korea", name: "South Korea", role: "external_power", region: "East Asia", flag: "🇰🇷",
    goals: "Energy security, frozen Iranian assets release, US alliance",
    redLines: "Strait of Hormuz disruption, Iranian nuclear test",
    preferredOutcomes: "Deescalation, asset unfreezing deal",
    constraints: "US alliance, frozen assets leverage held by Iran",
    communicationStyle: "Cautious US alignment, economic engagement",
  },
  {
    id: "global_north", name: "Global North Bloc", role: "global_bloc", region: "Global", flag: "🌐",
    goals: "Rules-based order, non-proliferation norms, energy price stability",
    redLines: "Nuclear weapons use, mass atrocities",
    preferredOutcomes: "Multilateral diplomatic resolution",
    constraints: "US unilateralism, internal divisions on Israel",
    communicationStyle: "UN Security Council multilateralism",
  },
  {
    id: "global_south_energy_importers", name: "Global South Energy Importers", role: "global_bloc", region: "Global", flag: "🌏",
    goals: "Low energy prices, food security, avoiding spillover instability",
    redLines: "Oil price spike above $120/barrel",
    preferredOutcomes: "Deescalation preserving oil market stability",
    constraints: "External debt, food import dependency",
    communicationStyle: "G77 collective advocacy",
  },
  {
    id: "global_south_energy_exporters", name: "Global South Energy Exporters", role: "global_bloc", region: "Global", flag: "🌍",
    goals: "High oil prices, OPEC+ cohesion, reduced Western energy sanctions leverage",
    redLines: "US military control of Middle East energy infrastructure",
    preferredOutcomes: "Controlled conflict maintaining elevated oil prices",
    constraints: "Carbon transition pressures, US dollar dependency",
    communicationStyle: "OPEC+ coordination, price management signaling",
  },
  {
    id: "iaea", name: "IAEA", role: "international_org", region: "Global", flag: "⚛️",
    goals: "Non-proliferation verification, access to Iranian nuclear sites, transparency",
    redLines: "Weaponization of nuclear material, inspector expulsion",
    preferredOutcomes: "Comprehensive safeguards agreement, enhanced monitoring regime",
    constraints: "No enforcement power, member-state political dynamics",
    communicationStyle: "Technical reports, Board of Governors resolutions",
  },
  {
    id: "iran_reformists", name: "Iran Reformist Faction", role: "internal_faction", region: "Middle East", flag: "🇮🇷",
    goals: "Sanctions relief, economic liberalization, reduced international isolation",
    redLines: "External regime change, capitulation on nuclear sovereignty",
    preferredOutcomes: "Pragmatic diplomacy leading to sanctions relief, JCPOA-style deal",
    constraints: "Suppressed by hardliners, limited electoral access post-2021",
    communicationStyle: "Indirect signaling via reformist media, technocratic framing",
  },
  {
    id: "iran_irgc", name: "IRGC Leadership", role: "internal_faction", region: "Middle East", flag: "🇮🇷",
    goals: "Regime survival, regional military dominance, economic empire via sanctions bypass",
    redLines: "Disarmament, loss of proxy network, opening of domestic economy to foreign control",
    preferredOutcomes: "Continued deterrence via nuclear ambiguity, controlled conflict",
    constraints: "Western sanctions pressure, internal economic discontent",
    communicationStyle: "Statements via state media, proxy escalation signals",
  },
];

export async function seedStakeholders(): Promise<void> {
  for (const s of STAKEHOLDERS) {
    await db.insert(stakeholdersTable).values(s).onConflictDoNothing();
  }
}
