import { db } from "@workspace/db";
import { stakeholdersTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const STAKEHOLDERS = [
  {
    id: "iran", name: "Iran", role: "core_principal", region: "Middle East", flag: "🇮🇷",
    tier: "required",
    goals: "Regime survival, nuclear deterrence, regional hegemony, sanction relief, non-aggression guarantees",
    redLines: "Regime change, full nuclear dismantlement, direct military attack on soil, future aggression without international guarantees against recurrence",
    preferredOutcomes: "Sanctions partial deal, regional framework recognizing Iranian sphere, binding international non-aggression pact with security guarantees",
    constraints: "Economic pressure, internal factional divisions, IRGC autonomy, demand for credible assurance that military aggression will never recur",
    communicationStyle: "Strategic ambiguity, calibrated escalation, back-channel diplomacy",
    profileSummary: "Seeks sanctions relief, nuclear recognition, no regime change threat. Demands binding non-aggression guarantees ensuring military aggression never recurs. Red lines: denuclearization, regime change, loss of deterrence, absence of security assurances.",
  },
  {
    id: "us", name: "United States", role: "core_principal", region: "North America", flag: "🇺🇸",
    tier: "required",
    goals: "Non-proliferation, regional stability, protecting Israel, allied reassurance",
    redLines: "Iranian nuclear weapon acquisition, direct attacks on US forces or allies",
    preferredOutcomes: "Sanctions partial deal or JCPOA-plus framework",
    constraints: "Domestic politics, congressional AIPAC pressure, allied coordination",
    communicationStyle: "Multilateral framing, maximum pressure alternating with dialogue",
    profileSummary: "Seeks verifiable denuclearization, regional security. Red lines: nuclear weapons capability, Hormuz blockade.",
  },
  {
    id: "israel", name: "Israel", role: "core_principal", region: "Middle East", flag: "🇮🇱",
    tier: "critical",
    goals: "Prevent Iranian nuclear capability, degrade proxy networks, maintain military superiority",
    redLines: "Iranian nuclear breakout, Hezbollah precision missiles targeting cities",
    preferredOutcomes: "Broad sanctions regime, military option preserved",
    constraints: "International legitimacy concerns, US approval for major operations",
    communicationStyle: "Deterrence signaling, unilateral action doctrine",
    profileSummary: "Opposes any deal that leaves Iran with enrichment capacity. Red line: any path to Iranian nuclear weapon. Borderline make-or-break — can undermine implementation unilaterally.",
  },
  {
    id: "saudi_arabia", name: "Saudi Arabia", role: "gulf_state", region: "Gulf", flag: "🇸🇦",
    tier: "influential",
    goals: "Counter Iranian influence, oil market stability, regional security architecture",
    redLines: "Iranian attack on Saudi infrastructure, Houthi escalation",
    preferredOutcomes: "Regional framework including Iranian recognition of Saudi sphere",
    constraints: "Vision 2030 economic diversification, OPEC coordination",
    communicationStyle: "Transactional diplomacy, bilateral over multilateral",
    profileSummary: "Seeks regional security guarantees, economic normalization. Concerned about Iranian influence in Yemen, Lebanon.",
  },
  {
    id: "uae", name: "United Arab Emirates", role: "gulf_state", region: "Gulf", flag: "🇦🇪",
    tier: "contextual",
    goals: "Trade hub stability, neutrality preservation, Iran economic channels",
    redLines: "Disruption of Strait of Hormuz, attack on UAE soil",
    preferredOutcomes: "Informal deescalation preserving trade access",
    constraints: "Significant Iranian trade volumes, Dubai financial hub concerns",
    communicationStyle: "Pragmatic hedging, discreet back-channels",
    profileSummary: "Trade hub stability, neutrality preservation, significant Iranian trade volumes. Strait of Hormuz exposure.",
  },
  {
    id: "qatar", name: "Qatar", role: "gulf_state", region: "Gulf", flag: "🇶🇦",
    tier: "contextual",
    goals: "Mediation role, gas export security, Hamas relations",
    redLines: "Forced alignment against Iran",
    preferredOutcomes: "Diplomatic framework with Qatar as key broker",
    constraints: "Shared North Dome/South Pars gas field with Iran",
    communicationStyle: "Active mediation, multi-directional diplomacy",
    profileSummary: "Mediation role, shared gas field with Iran. Multi-directional diplomacy, potential deal broker.",
  },
  {
    id: "oman", name: "Oman", role: "gulf_state", region: "Gulf", flag: "🇴🇲",
    tier: "contextual",
    goals: "Neutrality, back-channel facilitation, Strait of Hormuz security",
    redLines: "Being drawn into conflict",
    preferredOutcomes: "Quiet diplomacy leading to deescalation",
    constraints: "Geographic vulnerability, traditional neutral role",
    communicationStyle: "Quiet diplomacy, confidential facilitation",
    profileSummary: "Traditional neutral facilitator, Strait of Hormuz geography. Back-channel specialist.",
  },
  {
    id: "kuwait", name: "Kuwait", role: "gulf_state", region: "Gulf", flag: "🇰🇼",
    tier: "contextual",
    goals: "Security under US umbrella, stability, oil revenue",
    redLines: "Repeat of 1990 invasion scenario",
    preferredOutcomes: "US security guarantees maintained, regional stability",
    constraints: "Significant Shia population, border with Iraq",
    communicationStyle: "Cautious, multilateral coalition-building",
    profileSummary: "Security under US umbrella, stability-focused. Sensitive to regional invasion scenarios.",
  },
  {
    id: "bahrain", name: "Bahrain", role: "gulf_state", region: "Gulf", flag: "🇧🇭",
    tier: "contextual",
    goals: "Regime survival, US basing, countering Iranian influence on Shia population",
    redLines: "Iranian-backed domestic destabilization",
    preferredOutcomes: "Strong US security presence, Abraham Accords expansion",
    constraints: "Shia majority population, Iranian influence via religious networks",
    communicationStyle: "Strong alignment with US/Saudi position",
    profileSummary: "US naval base host. Concerned about Iranian influence on Shia majority population.",
  },
  {
    id: "egypt", name: "Egypt", role: "regional_broker", region: "North Africa", flag: "🇪🇬",
    tier: "contextual",
    goals: "Stability, Gaza ceasefire, canal revenues, avoiding regional spillover",
    redLines: "Destabilization of Gaza-Egypt border",
    preferredOutcomes: "Humanitarian mini-deal, Gaza ceasefire",
    constraints: "Economic fragility, Muslim Brotherhood suppression, US aid dependency",
    communicationStyle: "Pragmatic broker, ceasefire facilitation emphasis",
    profileSummary: "Regional stability, Gaza ceasefire, canal revenues. Pragmatic broker.",
  },
  {
    id: "turkey", name: "Turkey", role: "regional_broker", region: "Middle East", flag: "🇹🇷",
    tier: "contextual",
    goals: "Regional power projection, NATO hedging, economic relations with Iran",
    redLines: "Kurdish territorial gains, loss of Syria influence",
    preferredOutcomes: "Regional framework with Turkish mediator role",
    constraints: "NATO membership vs. Russia/Iran relations, Kurdish issue",
    communicationStyle: "Strategic autonomy, Erdogan personalist diplomacy",
    profileSummary: "NATO member with Iranian economic relations. Regional power seeking mediator role. Kurdish issue linkage.",
  },
  {
    id: "pakistan", name: "Pakistan", role: "regional_broker", region: "South Asia", flag: "🇵🇰",
    tier: "contextual",
    goals: "Avoid Iran-Pakistan border conflict, maintain economic corridor, serve as diplomatic bridge to China for guarantor role",
    redLines: "Iranian attack on Pakistani territory, exclusion from regional security framework",
    preferredOutcomes: "Deescalation with Pakistan-China axis providing security guarantees, China as deal guarantor",
    constraints: "Economic crisis, IMF dependency, internal instability, active diplomacy with China to position Beijing as guarantor",
    communicationStyle: "Cautious engagement, Islamic solidarity framing, China-aligned diplomatic outreach",
    profileSummary: "Iran border, economic corridor interests. Islamic solidarity framework. Actively engaging China to serve as guarantor in any peace deal framework.",
  },
  {
    id: "iraq", name: "Iraq", role: "regional_broker", region: "Middle East", flag: "🇮🇶",
    tier: "contextual",
    goals: "Avoid becoming battleground, Iranian and US engagement balance",
    redLines: "US or Iranian forces using Iraqi territory for attacks",
    preferredOutcomes: "Regional stability, Iraqi sovereignty respected",
    constraints: "PMF-Iranian ties, US troop presence, political fragmentation",
    communicationStyle: "Balancing act between Iran and US",
    profileSummary: "Caught between Iran/US. PMF-Iranian ties, US troop presence. Avoids becoming battleground.",
  },
  {
    id: "jordan", name: "Jordan", role: "regional_broker", region: "Middle East", flag: "🇯🇴",
    tier: "contextual",
    goals: "Palestinian state solution, regional stability, US support",
    redLines: "Mass Palestinian refugee influx, loss of Jerusalem custodianship",
    preferredOutcomes: "Two-state solution framework, Gaza humanitarian deal",
    constraints: "Palestinian refugee population, economic vulnerability",
    communicationStyle: "Moderate diplomatic voice, quiet US alignment",
    profileSummary: "Palestinian linkage, US support dependency. Regional stability buffer.",
  },
  {
    id: "lebanon", name: "Lebanon", role: "regional_broker", region: "Middle East", flag: "🇱🇧",
    tier: "contextual",
    goals: "Avoiding total Hezbollah-Israel war, economic survival",
    redLines: "Israeli ground invasion, complete economic collapse",
    preferredOutcomes: "Limited ceasefire, Hezbollah restraint deal",
    constraints: "Hezbollah dominance, state failure, economic crisis",
    communicationStyle: "Fragmented government, Hezbollah parallel governance",
    profileSummary: "Fragile state caught between Hezbollah and Israel. Economic survival priority.",
  },
  {
    id: "yemen", name: "Yemen (Houthis)", role: "regional_broker", region: "Middle East", flag: "🇾🇪",
    tier: "contextual",
    goals: "Recognition, end to Saudi blockade, solidarity with Palestinians",
    redLines: "Military defeat, total economic blockade",
    preferredOutcomes: "Negotiated end to war, Houthi political recognition",
    constraints: "Iranian proxy relationship, humanitarian catastrophe",
    communicationStyle: "Escalatory pressure via maritime attacks, propaganda",
    profileSummary: "Iranian-aligned proxy. Seeks recognition, uses maritime disruption as leverage.",
  },
  {
    id: "syria", name: "Syria", role: "regional_broker", region: "Middle East", flag: "🇸🇾",
    tier: "contextual",
    goals: "Reconstruction support, end to sanctions, territorial control",
    redLines: "Israeli annexation of Golan, renewed civil war",
    preferredOutcomes: "Deescalation, Arab League readmission",
    constraints: "Reconstruction dependency, Russian/Iranian presence",
    communicationStyle: "Cautious, dependent on Russian-Iranian support",
    profileSummary: "Post-conflict reconstruction needs. Dependent on Russian/Iranian presence.",
  },
  {
    id: "france", name: "France", role: "external_power", region: "Europe", flag: "🇫🇷",
    tier: "contextual",
    goals: "European strategic autonomy, JCPOA preservation, Lebanon influence",
    redLines: "Nuclear proliferation, attack on French citizens",
    preferredOutcomes: "Multilateral diplomatic framework, JCPOA revival",
    constraints: "EU cohesion, US alliance, domestic politics",
    communicationStyle: "Multilateral institution leadership, Élysée initiative",
    profileSummary: "E3 member. JCPOA advocate, Lebanon influence, European strategic autonomy.",
  },
  {
    id: "germany", name: "Germany", role: "external_power", region: "Europe", flag: "🇩🇪",
    tier: "contextual",
    goals: "JCPOA, non-proliferation, trade relations, regional stability",
    redLines: "Armed conflict threatening European security",
    preferredOutcomes: "Diplomatic resolution through E3+3 framework",
    constraints: "Post-WWII pacifism, EU partnership, US alliance",
    communicationStyle: "Economic diplomacy, multilateral consensus-building",
    profileSummary: "E3 member. Economic diplomacy, JCPOA framework advocate.",
  },
  {
    id: "uk", name: "United Kingdom", role: "external_power", region: "Europe", flag: "🇬🇧",
    tier: "contextual",
    goals: "Transatlantic alignment, non-proliferation, Gulf security",
    redLines: "Iranian nuclear weapon, attacks on UK assets",
    preferredOutcomes: "Diplomatic framework aligned with US",
    constraints: "Post-Brexit reduced EU influence, US dependency",
    communicationStyle: "Strong US alignment, active E3 participant",
    profileSummary: "E3 member. Strong US alignment, Gulf security interests.",
  },
  {
    id: "eu3", name: "EU (France/UK/Germany)", role: "external_power", region: "Europe", flag: "🇪🇺",
    tier: "influential",
    goals: "JCPOA preservation, strong verification, phased sanctions relief, trade mechanisms",
    redLines: "Nuclear proliferation, collapse of multilateral framework",
    preferredOutcomes: "Multilateral diplomatic resolution, JCPOA revival or successor",
    constraints: "Internal EU divisions, US alliance dependencies, economic exposure to sanctions",
    communicationStyle: "Multilateral E3+3 diplomacy, economic incentive packages",
    profileSummary: "Strong verification advocate, supports phased sanctions relief, key economic/trade mechanisms.",
  },
  {
    id: "russia", name: "Russia", role: "external_power", region: "Eurasia", flag: "🇷🇺",
    tier: "influential",
    goals: "Weaken US global position, arms sales, energy market share",
    redLines: "NATO expansion into Middle East, loss of Syrian base",
    preferredOutcomes: "Continued conflict draining US resources, Russian role preserved",
    constraints: "Ukraine war, sanctions, OPEC+ dynamics",
    communicationStyle: "Spoiler diplomacy, arms-supply leverage",
    profileSummary: "UNSC veto holder. Supports Iranian sovereignty, opposes Western-led sanctions. Can block/enable at UN level.",
  },
  {
    id: "china", name: "China", role: "external_power", region: "East Asia", flag: "🇨🇳",
    tier: "influential",
    goals: "Energy security, BRI expansion, reduce US regional dominance, potential guarantor role in Iran peace framework",
    redLines: "Conflict disrupting energy supplies or BRI",
    preferredOutcomes: "Saudi-Iran normalization maintained, regional stability, expanded influence as peace guarantor",
    constraints: "Non-interference principle, US trade war, Pakistan encouraging guarantor role",
    communicationStyle: "Multilateral non-interference, quiet influence expansion, guarantor diplomacy via Pakistan channel",
    profileSummary: "Major Iranian trade partner. Values economic ties, opposes sanctions, supports negotiated solution. BRI interests. Being approached by Pakistan to serve as guarantor in peace deal framework.",
  },
  {
    id: "india", name: "India", role: "external_power", region: "South Asia", flag: "🇮🇳",
    tier: "contextual",
    goals: "Energy security (Iranian oil), Chabahar port access, strategic autonomy",
    redLines: "Disruption of Chabahar corridor",
    preferredOutcomes: "Stable Iran for energy imports and trade routes",
    constraints: "US sanctions pressure, Hindu nationalist domestic politics",
    communicationStyle: "Strategic autonomy, balancing act between US and Iran",
    profileSummary: "Energy security (Iranian oil), Chabahar port access. Balancing US and Iran.",
  },
  {
    id: "japan", name: "Japan", role: "external_power", region: "East Asia", flag: "🇯🇵",
    tier: "contextual",
    goals: "Energy security (Gulf oil), maritime security, US alliance",
    redLines: "Strait of Hormuz closure",
    preferredOutcomes: "Deescalation, energy flow guaranteed",
    constraints: "Constitutional pacifism, complete US alliance dependency",
    communicationStyle: "Quiet mediation, economic diplomacy",
    profileSummary: "Strait of Hormuz oil dependency, constitutional pacifism. Quiet mediator.",
  },
  {
    id: "south_korea", name: "South Korea", role: "external_power", region: "East Asia", flag: "🇰🇷",
    tier: "contextual",
    goals: "Energy security, frozen Iranian assets release, US alliance",
    redLines: "Strait of Hormuz disruption, Iranian nuclear test",
    preferredOutcomes: "Deescalation, asset unfreezing deal",
    constraints: "US alliance, frozen assets leverage held by Iran",
    communicationStyle: "Cautious US alignment, economic engagement",
    profileSummary: "Frozen Iranian assets leverage, energy security. US-aligned but economically exposed.",
  },
  {
    id: "ukraine", name: "Ukraine", role: "external_power", region: "Europe", flag: "🇺🇦",
    tier: "contextual",
    goals: "End Russian aggression, restore territorial integrity, weaken Russia's military supply chain",
    redLines: "Any deal legitimizing Russian occupation, Iranian drone supply continuation",
    preferredOutcomes: "Iran peace reducing Russian access to Iranian military hardware (Shahed drones), weakening Russia's war capacity",
    constraints: "Active war with Russia, energy infrastructure 40%+ destroyed, Western aid dependency",
    communicationStyle: "Direct appeals to Western allies, Zelensky personal diplomacy, public accountability framing",
    profileSummary: "Wants to cut Iran-Russia military supply chain (Shahed drones). Active war with Russia shapes priorities.",
  },
  {
    id: "global_north", name: "Global North Bloc", role: "global_bloc", region: "Global", flag: "🌐",
    tier: "contextual",
    goals: "Rules-based order, non-proliferation norms, energy price stability",
    redLines: "Nuclear weapons use, mass atrocities",
    preferredOutcomes: "Multilateral diplomatic resolution",
    constraints: "US unilateralism, internal divisions on Israel",
    communicationStyle: "UN Security Council multilateralism",
    profileSummary: "Rules-based order, non-proliferation norms, energy price stability.",
  },
  {
    id: "global_south_energy_importers", name: "Global South Energy Importers", role: "global_bloc", region: "Global", flag: "🌏",
    tier: "contextual",
    goals: "Low energy prices, food security, avoiding spillover instability",
    redLines: "Oil price spike above $120/barrel",
    preferredOutcomes: "Deescalation preserving oil market stability",
    constraints: "External debt, food import dependency",
    communicationStyle: "G77 collective advocacy",
    profileSummary: "Low energy prices, food security. Oil spike above $120/bbl is red line.",
  },
  {
    id: "global_south_energy_exporters", name: "Global South Energy Exporters", role: "global_bloc", region: "Global", flag: "🌍",
    tier: "contextual",
    goals: "High oil prices, OPEC+ cohesion, reduced Western energy sanctions leverage",
    redLines: "US military control of Middle East energy infrastructure",
    preferredOutcomes: "Controlled conflict maintaining elevated oil prices",
    constraints: "Carbon transition pressures, US dollar dependency",
    communicationStyle: "OPEC+ coordination, price management signaling",
    profileSummary: "OPEC+ cohesion, elevated oil prices. Controlled conflict may serve their interests.",
  },
  {
    id: "iaea", name: "IAEA", role: "international_org", region: "Global", flag: "⚛️",
    tier: "influential",
    goals: "Non-proliferation verification, access to Iranian nuclear sites, transparency",
    redLines: "Weaponization of nuclear material, inspector expulsion",
    preferredOutcomes: "Comprehensive safeguards agreement, enhanced monitoring regime",
    constraints: "No enforcement power, member-state political dynamics",
    communicationStyle: "Technical reports, Board of Governors resolutions",
    profileSummary: "Verification authority. Supports snap inspections, continuous monitoring. Essential for implementation but not a party to the deal.",
  },
  {
    id: "iran_reformists", name: "Iran Reformist Faction", role: "internal_faction", region: "Middle East", flag: "🇮🇷",
    tier: "contextual",
    goals: "Sanctions relief, economic liberalization, reduced international isolation",
    redLines: "External regime change, capitulation on nuclear sovereignty",
    preferredOutcomes: "Pragmatic diplomacy leading to sanctions relief, JCPOA-style deal",
    constraints: "Suppressed by hardliners, limited electoral access post-2021",
    communicationStyle: "Indirect signaling via reformist media, technocratic framing",
    profileSummary: "Seeks sanctions relief and economic liberalization. Suppressed by hardliners.",
  },
  {
    id: "iran_irgc", name: "IRGC Leadership", role: "internal_faction", region: "Middle East", flag: "🇮🇷",
    tier: "contextual",
    goals: "Regime survival, regional military dominance, economic empire via sanctions bypass",
    redLines: "Disarmament, loss of proxy network, opening of domestic economy to foreign control",
    preferredOutcomes: "Continued deterrence via nuclear ambiguity, controlled conflict",
    constraints: "Western sanctions pressure, internal economic discontent",
    communicationStyle: "Statements via state media, proxy escalation signals",
    profileSummary: "Regime survival, regional military dominance. Opposes any deal weakening proxy networks.",
  },
];

export async function seedStakeholders(): Promise<void> {
  for (const s of STAKEHOLDERS) {
    await db.insert(stakeholdersTable).values(s).onConflictDoUpdate({
      target: stakeholdersTable.id,
      set: {
        name: sql`excluded.name`,
        role: sql`excluded.role`,
        region: sql`excluded.region`,
        flag: sql`excluded.flag`,
        tier: sql`excluded.tier`,
        communicationStyle: sql`excluded.communication_style`,
      },
    });
  }
}
