import type { Deal } from "@workspace/db/schema";

type DealScores = {
  feasibility?: number;
  coherence?: number;
  evidenceGrounding?: number;
  domesticSellability?: number;
  regionalStability?: number;
  implementability?: number;
  durability?: number;
  composite?: number;
  scoreRationale?: Record<string, string>;
  judgePanel?: Array<{ provider: string; model: string; scores: Record<string, number>; rationale: Record<string, string> }>;
};

type StakeholderEval = {
  verdict: string;
  rationale: string;
  redLineViolations?: string[];
  conditions?: string[];
};

type DomesticEval = {
  audience: string;
  verdict: string;
  rationale: string;
};

type DomesticFraming = {
  audience: string;
  framingNarrative: string;
  keyTalkingPoints: string[];
  historicalAnalogy?: string;
  riskOfBackfire: string;
};

type RedTeamResult = {
  attack: string;
  severity: string;
  response: string;
  survived: boolean;
};

type NegotiatorResult = {
  proposedAmendments: Array<{
    stakeholder: string;
    originalConcern: string;
    proposedChange: string;
    likelihood: string;
  }>;
  revisedTermsPartial: Record<string, unknown>;
  negotiationStrategy: string;
  creativeTradeoffs?: Array<{
    gives: string;
    gets: string;
    netBenefit: string;
  }>;
};

type BrainstormInsights = {
  historicalAnalogies: Array<{ dealName: string; relevantLesson: string; applicability: string }>;
  creativeProvisions: Array<{ idea: string; rationale: string; noveltyLevel: string }>;
  crossIssueLinkages: Array<{ linkage: string; stakeholdersHelped: string[] }>;
  unconventionalApproaches: string[];
};

type InnovativeProvision = {
  title: string;
  description: string;
  rationale: string;
  historicalPrecedent?: string;
};

function pct(v: number | undefined | null): string {
  if (v === null || v === undefined) return "N/A";
  return `${(v * 100).toFixed(1)}%`;
}

function formatDate(d: Date | string): string {
  const dt = new Date(d);
  return dt.toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short",
  });
}

export function dealToMarkdown(deal: Deal, permalinkUrl: string): string {
  const terms = deal.terms as Record<string, unknown>;
  const scores = deal.scores as DealScores | null;
  const stakeholderEvals = (deal.stakeholderEvaluations ?? {}) as Record<string, StakeholderEval>;
  const domesticEvals = (deal.domesticEvaluations ?? {}) as Record<string, DomesticEval>;
  const domesticFraming = ((deal as Record<string, unknown>).domesticFramingStrategies ?? {}) as Record<string, DomesticFraming>;
  const redTeamResults = (deal.redTeamResults ?? []) as RedTeamResult[];
  const negotiatorResult = deal.negotiatorResult as NegotiatorResult | null;
  const brainstormInsights = (deal as Record<string, unknown>).brainstormInsights as BrainstormInsights | null;
  const innovativeProvisions = (terms.innovativeProvisions ?? []) as InnovativeProvision[];
  const stakeholderCommitments = (terms.stakeholderCommitments ?? {}) as Record<string, string>;

  const lines: string[] = [];

  lines.push(`# AI-Generated Peace Deal Proposal`);
  lines.push(``);
  lines.push(`> This proposed peace deal for the Iran-US-Israel conflict was generated by a sophisticated AI system on AutoPeace.org based on accumulated evidence on ${formatDate(deal.createdAt)}.`);
  lines.push(``);
  lines.push(`**Permalink:** ${permalinkUrl}`);
  lines.push(`**LLM-readable version:** ${permalinkUrl.replace(/\/deals\//, "/api/deals/")}/llm.md`);
  lines.push(``);

  lines.push(`## Metadata`);
  lines.push(``);
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Deal ID | \`${deal.id}\` |`);
  lines.push(`| Architecture | ${deal.architecture} |`);
  lines.push(`| Generated By | ${deal.generatedBy} |`);
  lines.push(`| Created At | ${formatDate(deal.createdAt)} |`);
  lines.push(`| Is Current Champion | ${deal.isCurrent ? "Yes" : "No"} |`);
  lines.push(`| Pareto Optimal | ${deal.isPareto ? "Yes" : "No"} |`);
  if (deal.tokensConsumed) lines.push(`| Tokens Consumed | ${deal.tokensConsumed.toLocaleString()} |`);
  if (deal.costUsd) lines.push(`| Cost (USD) | $${deal.costUsd.toFixed(4)} |`);
  lines.push(``);

  lines.push(`## Deal Terms`);
  lines.push(``);
  const termFields = [
    { label: "Nuclear Protocol", key: "nuclearProtocol" },
    { label: "Sanctions Relief", key: "sanctionsRelief" },
    { label: "Maritime Security (Hormuz)", key: "hormuzArrangements" },
    { label: "Humanitarian Provisions", key: "humanitarianProvisions" },
    { label: "Verification Mechanism", key: "verificationMechanism" },
    { label: "Timeline (Years)", key: "timelineYears" },
    { label: "Sequencing", key: "sequencing" },
  ];
  for (const { label, key } of termFields) {
    const val = terms[key];
    if (val !== undefined && val !== null) {
      lines.push(`### ${label}`);
      lines.push(``);
      lines.push(`${String(val)}`);
      lines.push(``);
    }
  }

  if (terms.additionalClauses && Array.isArray(terms.additionalClauses) && terms.additionalClauses.length > 0) {
    lines.push(`### Additional Clauses`);
    lines.push(``);
    for (const clause of terms.additionalClauses as string[]) {
      lines.push(`- ${clause}`);
    }
    lines.push(``);
  }

  if (Object.keys(stakeholderCommitments).length > 0) {
    lines.push(`### Grand Coalition Stakeholder Commitments`);
    lines.push(``);
    for (const [id, commitment] of Object.entries(stakeholderCommitments)) {
      lines.push(`- **${id.replace(/_/g, " ")}**: ${commitment}`);
    }
    lines.push(``);
  }

  if (innovativeProvisions.length > 0) {
    lines.push(`### Innovative Provisions`);
    lines.push(``);
    for (const prov of innovativeProvisions) {
      lines.push(`#### ${prov.title}`);
      lines.push(``);
      lines.push(`${prov.description}`);
      lines.push(``);
      lines.push(`*Rationale:* ${prov.rationale}`);
      if (prov.historicalPrecedent) {
        lines.push(`*Historical Precedent:* ${prov.historicalPrecedent}`);
      }
      lines.push(``);
    }
  }

  if (scores) {
    lines.push(`## Scores (7-Dimension Evaluation)`);
    lines.push(``);
    lines.push(`| Dimension | Score | Rating |`);
    lines.push(`|-----------|-------|--------|`);
    const dims: { key: keyof DealScores; label: string }[] = [
      { key: "feasibility", label: "Feasibility" },
      { key: "coherence", label: "Coherence" },
      { key: "evidenceGrounding", label: "Evidence Grounding" },
      { key: "domesticSellability", label: "Domestic Sellability" },
      { key: "regionalStability", label: "Regional Stability" },
      { key: "implementability", label: "Implementability" },
      { key: "durability", label: "Durability" },
    ];
    for (const { key, label } of dims) {
      const v = scores[key];
      const rating = v === undefined || v === null ? "N/A" : v >= 0.65 ? "Viable" : v >= 0.45 ? "Marginal" : "Weak";
      lines.push(`| ${label} | ${pct(v)} | ${rating} |`);
    }
    lines.push(`| **Composite** | **${pct(scores.composite)}** | ${scores.composite !== undefined && scores.composite !== null ? (scores.composite >= 0.65 ? "**Viable**" : scores.composite >= 0.45 ? "**Marginal**" : "**Weak**") : "N/A"} |`);
    lines.push(``);

    const rationale = scores.scoreRationale;
    if (rationale && Object.keys(rationale).length > 0) {
      lines.push(`### Score Rationales`);
      lines.push(``);
      for (const { key, label } of dims) {
        if (rationale[key]) {
          lines.push(`**${label}:** ${rationale[key]}`);
          lines.push(``);
        }
      }
    }

    if (scores.judgePanel && scores.judgePanel.length > 0) {
      lines.push(`### Judge Panel (Multi-Model Evaluation)`);
      lines.push(``);
      for (const judge of scores.judgePanel) {
        lines.push(`#### ${judge.provider} — ${judge.model}`);
        lines.push(``);
        for (const { key, label } of dims) {
          const jScore = judge.scores[key];
          const jRationale = judge.rationale?.[key];
          if (jScore !== undefined) {
            lines.push(`- **${label}:** ${pct(jScore)}${jRationale ? ` — ${jRationale}` : ""}`);
          }
        }
        lines.push(``);
      }
    }
  }

  if (Object.keys(stakeholderEvals).length > 0) {
    lines.push(`## Stakeholder Evaluations`);
    lines.push(``);
    const accepts = Object.values(stakeholderEvals).filter(e => e.verdict === "accept").length;
    const conditionals = Object.values(stakeholderEvals).filter(e => e.verdict === "conditional").length;
    const rejects = Object.values(stakeholderEvals).filter(e => e.verdict === "reject").length;
    lines.push(`**Summary:** ${accepts} Accept · ${conditionals} Conditional · ${rejects} Reject (${Object.keys(stakeholderEvals).length} stakeholders evaluated)`);
    lines.push(``);
    for (const [id, ev] of Object.entries(stakeholderEvals)) {
      lines.push(`### ${id.replace(/[_-]/g, " ").replace(/\b\w/g, c => c.toUpperCase())}`);
      lines.push(``);
      lines.push(`- **Verdict:** ${ev.verdict.toUpperCase()}`);
      lines.push(`- **Rationale:** ${ev.rationale}`);
      if (ev.redLineViolations && ev.redLineViolations.length > 0) {
        lines.push(`- **Red Line Violations:** ${ev.redLineViolations.join("; ")}`);
      }
      if (ev.conditions && ev.conditions.length > 0) {
        lines.push(`- **Conditions:** ${ev.conditions.join("; ")}`);
      }
      lines.push(``);
    }
  }

  if (Object.keys(domesticEvals).length > 0) {
    lines.push(`## Domestic Sellability Evaluations`);
    lines.push(``);
    for (const [key, ev] of Object.entries(domesticEvals)) {
      lines.push(`### ${ev.audience || key}`);
      lines.push(``);
      lines.push(`- **Verdict:** ${ev.verdict}`);
      lines.push(`- **Rationale:** ${ev.rationale}`);
      lines.push(``);
    }
  }

  if (Object.keys(domesticFraming).length > 0) {
    lines.push(`## AI Creative Framing Strategies`);
    lines.push(``);
    for (const [, strategy] of Object.entries(domesticFraming)) {
      lines.push(`### ${strategy.audience}`);
      lines.push(``);
      lines.push(`*"${strategy.framingNarrative}"*`);
      lines.push(``);
      if (strategy.keyTalkingPoints?.length > 0) {
        lines.push(`**Key Talking Points:**`);
        for (const pt of strategy.keyTalkingPoints) {
          lines.push(`- ${pt}`);
        }
        lines.push(``);
      }
      if (strategy.historicalAnalogy) {
        lines.push(`**Historical Analogy:** ${strategy.historicalAnalogy}`);
        lines.push(``);
      }
      lines.push(`**Risk of Backfire:** ${strategy.riskOfBackfire}`);
      lines.push(``);
    }
  }

  if (redTeamResults.length > 0) {
    const survived = redTeamResults.filter(r => r.survived).length;
    lines.push(`## Red Team Stress Test`);
    lines.push(``);
    lines.push(`**Results:** ${survived}/${redTeamResults.length} attacks survived`);
    lines.push(``);
    for (const r of redTeamResults) {
      lines.push(`### Attack: ${r.attack}`);
      lines.push(``);
      lines.push(`- **Severity:** ${r.severity}`);
      lines.push(`- **Outcome:** ${r.survived ? "SURVIVED" : "FAILED"}`);
      if (r.response) lines.push(`- **Response:** ${r.response}`);
      lines.push(``);
    }
  }

  if (negotiatorResult) {
    lines.push(`## Negotiator Amendments`);
    lines.push(``);
    if (negotiatorResult.negotiationStrategy) {
      lines.push(`**Strategy:** ${negotiatorResult.negotiationStrategy}`);
      lines.push(``);
    }
    if (negotiatorResult.proposedAmendments?.length > 0) {
      lines.push(`### Proposed Amendments`);
      lines.push(``);
      for (const a of negotiatorResult.proposedAmendments) {
        lines.push(`- **${a.stakeholder}** (likelihood: ${a.likelihood})`);
        lines.push(`  - Concern: ${a.originalConcern}`);
        lines.push(`  - Proposed Change: ${a.proposedChange}`);
      }
      lines.push(``);
    }
    if (negotiatorResult.creativeTradeoffs && negotiatorResult.creativeTradeoffs.length > 0) {
      lines.push(`### Creative Tradeoffs`);
      lines.push(``);
      for (const t of negotiatorResult.creativeTradeoffs) {
        lines.push(`- **Gives:** ${t.gives} → **Gets:** ${t.gets} (Net benefit: ${t.netBenefit})`);
      }
      lines.push(``);
    }
  }

  if (brainstormInsights) {
    lines.push(`## AI Innovation Brainstorm`);
    lines.push(``);
    if (brainstormInsights.historicalAnalogies?.length > 0) {
      lines.push(`### Historical Analogies Applied`);
      lines.push(``);
      for (const a of brainstormInsights.historicalAnalogies) {
        lines.push(`- **${a.dealName}** — ${a.relevantLesson} (Applicability: ${a.applicability})`);
      }
      lines.push(``);
    }
    if (brainstormInsights.creativeProvisions?.length > 0) {
      lines.push(`### Creative Provisions`);
      lines.push(``);
      for (const p of brainstormInsights.creativeProvisions) {
        lines.push(`- **${p.idea}** [${p.noveltyLevel}] — ${p.rationale}`);
      }
      lines.push(``);
    }
    if (brainstormInsights.crossIssueLinkages?.length > 0) {
      lines.push(`### Cross-Issue Linkages`);
      lines.push(``);
      for (const l of brainstormInsights.crossIssueLinkages) {
        lines.push(`- ${l.linkage} (helps: ${l.stakeholdersHelped.join(", ")})`);
      }
      lines.push(``);
    }
    if (brainstormInsights.unconventionalApproaches?.length > 0) {
      lines.push(`### Unconventional Approaches`);
      lines.push(``);
      for (const u of brainstormInsights.unconventionalApproaches) {
        lines.push(`- ${u}`);
      }
      lines.push(``);
    }
  }

  if (deal.diagnosis) {
    lines.push(`## AI Diagnosis`);
    lines.push(``);
    lines.push(deal.diagnosis);
    lines.push(``);
  }

  if (deal.evidenceSummary) {
    lines.push(`## Evidence Context`);
    lines.push(``);
    lines.push(`The following evidence was used as context when generating this deal:`);
    lines.push(``);
    lines.push(deal.evidenceSummary);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`*Generated by AutoPeace — AI-powered conflict forecasting and peace research platform. Visit [AutoPeace.org](https://autopeace.org) for more.*`);

  return lines.join("\n");
}
